### ISSUE TITLE
Roadmap of fixes

### ISSUE THREAD

**Issue by zeffii** [MonZop/BioBlender#16]
---------------------------------
Feb 04 - 2015

The fixes I would like to pull into master soon are 
- [ ] `file_append -> dedicated function` to support versions all the way up to 2.73
- [ ] reference to `modelList` should be `tmpModel`
- [ ] add `pymol.cmd` as optional pymol path

**Comment by MonZop** [comment]
I do understand file_append and pymol.cmd, and agree.
I probably agree also with the modelList, but i do not understand this one :-(

**Comment by zeffii** [comment]
it's a typo by whoever wrote that code
